# Default Configuration for AMR Semantic Parsing Project
# ======================================================

# Model Configuration
model:
  model_name: "VietAI/vit5-base"
  max_length: 512
  batch_size: 8
  learning_rate: 5e-5
  num_epochs: 3
  warmup_steps: 500
  weight_decay: 0.01
  fp16: true
  gradient_accumulation_steps: 1
  eval_steps: 500
  save_steps: 500
  logging_steps: 100
  early_stopping_patience: 3
  num_beams: 4
  do_sample: false
  temperature: 1.0

# Data Configuration
data:
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  max_samples: null # null means use all samples
  shuffle: true
  random_seed: 42
  max_input_length: 512
  max_output_length: 512
  min_input_length: 1
  min_output_length: 1

# Training Configuration
training:
  use_wandb: false
  wandb_project: "amr-semantic-parsing"
  run_name: null
  resume_from_checkpoint: null
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  evaluation_strategy: "steps"
  lr_scheduler_type: "linear"
  dataloader_num_workers: 4

# Evaluation Configuration
evaluation:
  batch_size: 16
  metrics: ["bleu", "rouge", "meteor", "exact_match"]
  generate_report: true
  save_predictions: true

# Inference Configuration
inference:
  batch_size: 8
  max_length: 512
  num_beams: 4
  do_sample: false
  temperature: 1.0
  format_output: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  console_logging: true
  log_dir: "logs"

# Path Configuration
paths:
  data_dir: "data"
  train_dir: "data/train"
  test_dir: "data/test"
  processed_dir: "data/processed"
  model_dir: "models"
  output_dir: "models/amr_model"
  checkpoint_dir: "models/checkpoints"
  log_dir: "logs"
  cache_dir: ".cache"
