data:
  max_input_length: 256
  max_output_length: 256
  max_samples: 100
  test_ratio: 0.05
  train_ratio: 0.8
  val_ratio: 0.15
model:
  eval_steps: 50
  fp16: false
  learning_rate: 5.0e-05
  logging_steps: 10
  max_length: 256
  model_name: VietAI/vit5-base
  num_train_epochs: 2
  per_device_eval_batch_size: 4
  per_device_train_batch_size: 2
  save_steps: 50
  warmup_steps: 100
paths:
  log_dir: logs/local
  output_dir: models/amr_local_model
  processed_dir: data/processed
training:
  dataloader_num_workers: 0
  report_to: none
  run_name: local-amr-training
  use_wandb: false
