# Minimal Configuration - Just the essentials
# ==========================================

# Model Configuration - Minimal
model:
  model_name: "VietAI/vit5-base"
  max_length: 128
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  learning_rate: 0.00005  # Use decimal instead of scientific notation
  num_train_epochs: 1
  warmup_steps: 5
  weight_decay: 0.01
  fp16: false
  gradient_accumulation_steps: 1
  eval_steps: 5
  save_steps: 5
  logging_steps: 1
  early_stopping_patience: 0  # Disable early stopping
  early_stopping_threshold: 0.001
  adam_epsilon: 0.00000001  # Use decimal
  max_grad_norm: 1.0
  lr_scheduler_type: "linear"
  evaluation_strategy: "steps"
  save_total_limit: 1
  load_best_model_at_end: false  # Disable for simplicity
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  report_to: "none"
  run_name: "minimal-test"
  seed: 42
  dataloader_num_workers: 0
  logging_dir: "logs/minimal"
  output_dir: "models/minimal_model"
  max_input_length: 128
  max_output_length: 128

# Data Configuration - Minimal
data:
  train_ratio: 0.8
  val_ratio: 0.2
  test_ratio: 0.0  # No test for minimal
  max_samples: 10  # Very small
  shuffle_data: true
  random_seed: 42
  max_input_length: 128
  max_output_length: 128
  min_input_length: 1
  min_output_length: 1
  train_data_path: "data/train"
  test_data_path: "data/test"
  processed_data_dir: "data/processed"

# Training Configuration - Minimal
training:
  use_wandb: false
  wandb_project: "minimal-test"
  run_name: "minimal-run"
  resume_from_checkpoint: null
  save_total_limit: 1
  load_best_model_at_end: false
  metric_for_best_model: "eval_loss"
  greater_is_better: false
  evaluation_strategy: "steps"
  lr_scheduler_type: "linear"
  dataloader_num_workers: 0

# Evaluation Configuration - Minimal
evaluation:
  batch_size: 1
  metrics: ["exact_match"]  # Just one metric
  generate_report: false
  save_predictions: false

# Inference Configuration - Minimal
inference:
  batch_size: 1
  max_length: 128
  num_beams: 1  # No beam search
  do_sample: false
  temperature: 1.0
  format_output: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  console_logging: true
  log_dir: "logs/minimal"

# Path Configuration - Minimal
paths:
  data_dir: "data"
  train_dir: "data/train"
  test_dir: "data/test"
  processed_dir: "data/processed"
  model_dir: "models"
  output_dir: "models/minimal_model"
  checkpoint_dir: "models/checkpoints_minimal"
  log_dir: "logs/minimal"
  cache_dir: ".cache"
